spring:
  redis: # 网关自己的redis配置
    database: 0
    host: 127.0.0.1
    port: 6379
    system: # macula-cloud的system模块的redis配置
      database: 0
      host: 10.94.108.61
      port: 6380
      password: maculaV5@2023
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.config.server-addr}
        namespace: ${nacos.config.namespace}
        # group:
    sentinel:
      enabled: false
    gateway:
      routes:
        - id: macula-samples-openapi
          uri: lb://macula-samples-openapi
          predicates:
            - Path=/openapi/**
          filters:
            - StripPrefix=1
        - id: macula-samples-service2
          uri: lb://macula-samples-service2
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1
        - id: admin
          uri: lb://macula-samples-service2
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: client
          client-secret: secret
          introspection-uri: https://goauth-dev.infinitus.com.cn/introspect
macula:
  gateway:
    security:
      only-auth-urls: /api/**

logging:
  level:
    root: info
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
